a.out: main.o create_database.o display.o save.o search.o update.o validate.o
	gcc -o a.out main.o create_database.o display.o save.o search.o update.o validate.o
main.o: main.c
	gcc -c main.c
create_database.o:create_database.c
	gcc -c create_database.c
display.o:display.c
	gcc -c display.c
save.o:save.c
	gcc -c save.c
search.o:search.c
	gcc -c search.c
update.o:update.c
	gcc -c update.c
validate.o:validate.c
	gcc -c validate.c
clean:
	rm *.out *.o
